name: Reusable Workflow Caller (User)
on:

  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  original:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo The line in original workflow.

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
  call-workflow:
    needs: original
    uses: ChJL/workflow-test/.github/workflows/reusable_called.yml@main

  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
  
  auto-release:
    needs: 
      - call-workflow
      - create-tag
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"
          echo ${{ needs.createdtag.outputs.tagname }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ needs.create-tag.outputs.tagname }}
  
