name: Caller
on:
  push:
    branches: [ main ]
jobs:
  create-new-tag:
    name: 'create_tags'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    uses: ChJL/workflow-test/.github/workflows/git_tag.yml@main

  check-tag-name:
    needs: create-new-tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ needs.create-new-tag.outputs.new_tag }}"
          echo "Got release version ${{ needs.create-new-tag.outputs.new_version }}"
          echo "Got previous version ${{ needs.create-new-tag.outputs.previous_version }}"
          echo "Got previous tag ${{ needs.create-new-tag.outputs.previous_tag }}"
          echo "Got release type ${{ needs.create-new-tag.outputs.release_type }}"
          echo "Got changelog ${{ needs.create-new-tag.outputs.changelog }}"


#   # This section can be used when you want to delete the tag
#   # Remember to set the condition (e.g. if: )
#   delete-tag:
#      needs: create-new-tag
#      runs-on: ubuntu-latest
#      steps:
#      - name: checkout
#        uses: actions/checkout@v2.4.0
#        with:
#           token: ${{ secrets.GH_TOKEN }}
#      - name: delete tag command
#        run: |
#           git push --delete origin ${{ needs.create-new-tag.outputs.new_tag }}
        
  update-toml:
    needs: create-new-tag
    if: ${{ needs.create-new-tag.outputs.new_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Edit Toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "./pyproject.toml"
          key: "tool.poetry.version"
          value: "needs.create-new-tag.outputs.new_version"
  
  create-release:
    needs:
      - update-toml
      - create-new-tag
    if: ${{ needs.create-new-tag.outputs.new_tag }}
    uses: ChJL/workflow-test/.github/workflows/git_release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      TAG: ${{ needs.create-new-tag.outputs.new_tag }}
      CHANGELOG: ${{ needs.create-new-tag.outputs.changelog }}
