# name: Reusable Workflow Caller (User)
# on:

#   push:
#     branches: [ main ]
#     tags:
#       - "v*"

#   workflow_dispatch:
# jobs:
#   original:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Run a one-line script
#         run: echo The line in original workflow.

#   call-workflow:
#     needs: original
#     uses: ChJL/workflow-test/.github/workflows/reusable_called.yml@main


#   Release:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           body: |
#             Changes in this Release
#             - First Change
#             - Second Change
#           draft: false
#           prerelease: false

name: Bump version
on:
  push:
    branches: [ main ]
jobs:
  create-new-tag:
    name: 'create_tags'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    uses: ChJL/workflow-test/.github/workflows/git_tag.yml@main

  check-tag-name:
    needs: create-new-tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ needs.create-new-tag.outputs.new_tag }}"
          echo "Got release version ${{ needs.create-new-tag.outputs.new_version }}"
          echo "Got previous version ${{ needs.create-new-tag.outputs.previous_version }}"
          echo "Got previous tag ${{ needs.create-new-tag.outputs.previous_tag }}"
          echo "Got release type ${{ needs.create-new-tag.outputs.release_type }}"
          echo "Got changelog ${{ needs.create-new-tag.outputs.changelog }}"
          
  delete-tag:
     needs: create-new-tag
     runs-on: ubuntu-latest
     steps:
      - name: delete tag command
        run: |
          git push --delete origin ${{ needs.create-new-tag.outputs.new_tag }}
        
     
  create-release:
    needs: create-new-tag
    uses: ChJL/workflow-test/.github/workflows/git_release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      TAG: ${{ needs.create-new-tag.outputs.new_tag }}
      CHANGELOG: ${{ needs.create-new-tag.outputs.changelog }}
