name: Caller
on:
  push:
    branches: [main]
jobs:
  check-commit-message:
    outputs:
      tag: ${{steps.taketag.outputs.tag}}
    if: contains(github.event.head_commit.message, 'Bump version in pyproject.toml')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Retrieve tag
        id: taketag
        run: |
          git describe --tags --abbrev=0
          GIT_TAG=`echo $(git describe --tags --abbrev=0)`
          echo ::set-output name=tag::$GIT_TAG
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Check output
        run: |
          echo ${{ steps.taketag.outputs.tag}}

  compute-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Update tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: name-of-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
