name: Caller
on:
  push:
    branches: [ main ]
jobs:
  create-new-tag:
    name: 'create_tags'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    uses: ChJL/workflow-test/.github/workflows/git_tag.yml@main

  check-tag-name:
    needs: create-new-tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ needs.create-new-tag.outputs.new_tag }}"
          echo "Got release version ${{ needs.create-new-tag.outputs.new_version }}"
          echo "Got previous version ${{ needs.create-new-tag.outputs.previous_version }}"
          echo "Got previous tag ${{ needs.create-new-tag.outputs.previous_tag }}"
          echo "Got release type ${{ needs.create-new-tag.outputs.release_type }}"
          echo "Got changelog ${{ needs.create-new-tag.outputs.changelog }}"
  pytype:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        poetry-version: [1.1.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Update poetry version
        run: |
          poetry self update

#   # This section can be used when you want to delete the tag
#   # Remember to set the condition (e.g. if: )
#   delete-tag:
#      needs: create-new-tag
#      runs-on: ubuntu-latest
#      steps:
#      - name: checkout
#        uses: actions/checkout@v2.4.0
#        with:
#           token: ${{ secrets.GH_TOKEN }}
#      - name: delete tag command
#        run: |
#           git push --delete origin ${{ needs.create-new-tag.outputs.new_tag }}
        
     
  create-release:
    needs:
      - create-new-tag
    if: ${{ needs.create-new-tag.outputs.new_tag }}
    uses: ChJL/workflow-test/.github/workflows/git_release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      TAG: ${{ needs.create-new-tag.outputs.new_tag }}
      CHANGELOG: ${{ needs.create-new-tag.outputs.changelog }}
