name: Reusable Workflow Caller (User)
on:

  push:
    branches: [ main ]
    tags:
      - "v*"

  workflow_dispatch:
jobs:
  original:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo The line in original workflow.

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
  call-workflow:
    needs: original
    uses: ChJL/workflow-test/.github/workflows/reusable_called.yml@main

#   create-tag:
#     runs-on: ubuntu-latest
#     steps: 
#     - uses: actions/checkout@v2
#     - name: Auto tag
#       id: autotag
#       uses: Klemensas/action-autotag@stable
#       with:
#         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#         tag_prefix: "v"
#   auto-release:
#     needs: 
#       - call-workflow
#       - create-tag
#     name: "Tagged Release"
#     runs-on: "ubuntu-latest"


  Release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
