on:
  push:
    branches:
      - main
jobs:
  create-new-tag:
    if: "!contains(github.event.head_commit.message, 'pyproject version')"
    name: 'create_tags'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    uses: ChJL/workflow-test/.github/workflows/git_tag.yml@main


  simulate-push-to-ecr:
    needs:
      - create-new-tag
    runs-on: ubuntu-latest
    steps:
      - name: Simulate succeess or failure
        run: |
          echo "ecr fail!"
          exit 1


  delete-tag:
    needs:
      - simulate-push-to-ecr
      - create-new-tag
    if: "always() || (needs.simulate-push-to-ecr.result == 'failure')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: delete tag command
        if: "${{needs.create-new-tag.outputs.new_tag}}"
        run: |
          git push --delete origin ${{needs.create-new-tag.outputs.new_tag}}

  create-release:
    needs:
      - create-new-tag
      - simulate-push-to-ecr
      - delete-tag
    if: "(needs.simulate-push-to-ecr.result == 'success') && (needs.create-new-tag.outputs.new_tag != '')"
    uses: ChJL/workflow-test/.github/workflows/git_release.yml@main
    with:
      TAG: ${{ needs.create-new-tag.outputs.new_tag }}
      CHANGELOG: ${{ needs.create-new-tag.outputs.changelog }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
