on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      new_tag:
        description: 'New tag created by the workflow.'
        value: ${{ steps.tag_version.outputs.new_tag }}
      release_version:
        description: 'Release version going to be created.'
        value: ${{ steps.tag_version.outputs.new_tag }}
      previous_version:
        description: 'Previous version created.'
        value: ${{ steps.tag_version.outputs.new_tag }}
      previous_tag:
        description: 'Previous tag created.'
        value: ${{ steps.tag_version.outputs.new_tag }}
      release_type:
        description: 'Type of release created.'
        value: ${{ steps.tag_version.outputs.new_tag }}
      changelog:
        description: 'Release changelog.'
        value: ${{ steps.tag_version.outputs.new_tag }}

jobs:
  dash-create-tag:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          # set to false, to avoid releasing without any fix, feature. So the new_tag will be none.

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.tag_version.outputs.new_tag }}"
          echo "Got release version ${{ steps.tag_version.outputs.new_version }}"
          echo "Got previous version ${{ steps.tag_version.outputs.previous_version }}"
          echo "Got previous tag ${{ steps.tag_version.outputs.previous_tag }}"
          echo "Got release type ${{ steps.tag_version.outputs.release_type }}"
          echo "Got changelog ${{ steps.tag_version.outputs.changelog }}"
