on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      TAG:
        type: string
        required: true
#       CHANGELOG:
#         type: string
#         required: true

jobs:
  git-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Create a GitHub release
        if: ${{ inputs.TAG }}
        # Only if we have new tag(version), release the new version.
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.TAG }}
          name: Release ${{ inputs.TAG }}
